### ISSUE TITLE
Improve task that handles iptables rules

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/automation-tools#226]
Is there anything we can do to avoid seeing issues such as:

    out: Error: Execution of '/sbin/iptables -t filter -D INPUT -i virbr0 -p tcp -m tcp --dport 53 -j ACCEPT' returned 1: iptables: Bad rule (does a matching rule exist in that chain?).

I believe that running that task multiple times is what causes it. Preferably, this task should be 'smart' enough to only add a new rule if it isn't already in place?

**Comment by elyezer** [comment]
We already do that https://github.com/SatelliteQE/automation-tools/blob/master/automation_tools/__init__.py#L356

**Comment by sthirugn** [comment]
@elyezer: The issue which @omaciel mentions is still happening in our jenkins installer.  But it is not happening due to iptables changes from our script as mentioned in this issue - Rather it is being thrown by the katellovirt puppet module which we use - specifically https://github.com/SatelliteQE/automation-tools/blob/master/automation_tools/__init__.py#L258

Please see the latest installer job runs to see this error.  I am reopening this issue for now.

**Comment by elyezer** [comment]
@sthirugn we need to fix that message on the puppet module, there is nothing that we can do here. Is better to ensure the rules by our task and the module would have a better way to identify if the rule is already set or not.

With that said I still think that this can be closed.

**Comment by sthirugn** [comment]
@elyezer agreed, this is the problem with the puppet module itself and not our code.
