### ISSUE TITLE
Use robottelo's bz functions in provision-time

### ISSUE THREAD

**Issue by lpramuk** [SatelliteQE/automation-tools#394]
Sometimes we need to drive Satellite installation/postinstallation accordingly to bugzilla/redmine issue statuses.

For better picture I want to use such code in postinstall:
```
if os.environ.get('PXE_DEFAULT_TEMPLATE_URL') is not None:
    # for upstream skip until #16362 is fixed
    if not distribution.endswith('upstream') or not rm_bug_is_open(16362):
        execute(setup_foreman_discovery, host=host)
```

Lets discus how we can achieve it also in automation-tools. 
DRY vs. WET

**Comment by lpramuk** [comment]
I would go WET to enjoy typing. But lets wait for other ideas :)

**Comment by rplevka** [comment]
this might be sort of hard to maintain, but maybe the BZ/RM-related helper functions from `robottelo.decorators` should be packaged as a standalone module which might be stated in `requirements.txt` for both `robottelo` and `automation_tools` in order to follow DRY concept.

having `robottelo` being put in `requirements.txt` for `automation_tools` is much simpler and less 'bureau-crazy' but it is quite an overkill.

Otherwise I vote for WET :)

**Comment by lpramuk** [comment]
I'm not sure if ```pip install robottelo``` is possible

**Comment by rochacbruno** [comment]
I vote WET (robottelo's `bz_bug_is_open` uses `settings` which robottelo only object, also the only thing the function really does is calling `python-bugzilla.RHBugzilla().getbugsimple()` which is already external dependency

**Comment by lpramuk** [comment]
I WETed it out already in PR#399
